/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as CierreRouteImport } from './routes/cierre'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RemitosRouteImport } from './routes/remitos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as FacturaIdRouteImport } from './routes/factura.$id'
import { Route as RemitosIdRouteImport } from './routes/remitos.$id'
import { Route as TicketCobroIdRouteImport } from './routes/ticket.$cobroId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiMercadoV1SplatRouteImport } from './routes/api/mercado/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const CierreRoute = CierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RemitosRoute = RemitosRouteImport.update({
  id: '/remitos',
  path: '/remitos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturaIdRoute = FacturaIdRouteImport.update({
  id: '/factura/$id',
  path: '/factura/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemitosIdRoute = RemitosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RemitosRoute,
} as any)
const TicketCobroIdRoute = TicketCobroIdRouteImport.update({
  id: '/ticket/$cobroId',
  path: '/ticket/$cobroId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadoV1SplatRoute = ApiMercadoV1SplatRouteImport.update({
  id: '/api/mercado/v1/$',
  path: '/api/mercado/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/mercado/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/mercado/v1/$'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/mercado/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CajaRoute: typeof CajaRoute
  CierreRoute: typeof CierreRoute
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RemitosRoute: typeof RemitosRouteWithChildren
  UsuariosRoute: typeof UsuariosRoute
  VendedorRoute: typeof VendedorRoute
  FacturaIdRoute: typeof FacturaIdRoute
  TicketCobroIdRoute: typeof TicketCobroIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiMercadoV1SplatRoute: typeof ApiMercadoV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cierre': {
      id: '/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof CierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remitos': {
      id: '/remitos'
      path: '/remitos'
      fullPath: '/remitos'
      preLoaderRoute: typeof RemitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factura/$id': {
      id: '/factura/$id'
      path: '/factura/$id'
      fullPath: '/factura/$id'
      preLoaderRoute: typeof FacturaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remitos/$id': {
      id: '/remitos/$id'
      path: '/$id'
      fullPath: '/remitos/$id'
      preLoaderRoute: typeof RemitosIdRouteImport
      parentRoute: typeof RemitosRoute
    }
    '/ticket/$cobroId': {
      id: '/ticket/$cobroId'
      path: '/ticket/$cobroId'
      fullPath: '/ticket/$cobroId'
      preLoaderRoute: typeof TicketCobroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercado/v1/$': {
      id: '/api/mercado/v1/$'
      path: '/api/mercado/v1/$'
      fullPath: '/api/mercado/v1/$'
      preLoaderRoute: typeof ApiMercadoV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RemitosRouteChildren {
  RemitosIdRoute: typeof RemitosIdRoute
}

const RemitosRouteChildren: RemitosRouteChildren = {
  RemitosIdRoute: RemitosIdRoute,
}

const RemitosRouteWithChildren =
  RemitosRoute._addFileChildren(RemitosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CajaRoute: CajaRoute,
  CierreRoute: CierreRoute,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RemitosRoute: RemitosRouteWithChildren,
  UsuariosRoute: UsuariosRoute,
  VendedorRoute: VendedorRoute,
  FacturaIdRoute: FacturaIdRoute,
  TicketCobroIdRoute: TicketCobroIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiMercadoV1SplatRoute: ApiMercadoV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
