/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcaRouteImport } from './routes/arca'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as CierreRouteImport } from './routes/cierre'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ContratoRouteImport } from './routes/contrato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RemitosRouteImport } from './routes/remitos'
import { Route as TorreRouteImport } from './routes/torre'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as FacturaIdRouteImport } from './routes/factura.$id'
import { Route as RemitosIdRouteImport } from './routes/remitos.$id'
import { Route as TicketCobroIdRouteImport } from './routes/ticket.$cobroId'
import { Route as TorreIndexRouteImport } from './routes/torre.index'
import { Route as TorreAppsRouteImport } from './routes/torre.apps'
import { Route as TorreAuditoriaRouteImport } from './routes/torre.auditoria'
import { Route as TorreClientesRouteImport } from './routes/torre.clientes'
import { Route as TorreConfiguracionRouteImport } from './routes/torre.configuracion'
import { Route as TorreDeploymentsRouteImport } from './routes/torre.deployments'
import { Route as TorreFinanzasRouteImport } from './routes/torre.finanzas'
import { Route as TorreLegalRouteImport } from './routes/torre.legal'
import { Route as TorreLoginRouteImport } from './routes/torre.login'
import { Route as TorrePlanesRouteImport } from './routes/torre.planes'
import { Route as TorreProcesadoresRouteImport } from './routes/torre.procesadores'
import { Route as TorreProductosRouteImport } from './routes/torre.productos'
import { Route as TorrePromocionesRouteImport } from './routes/torre.promociones'
import { Route as TorrePublicidadRouteImport } from './routes/torre.publicidad'
import { Route as TorreServiciosRouteImport } from './routes/torre.servicios'
import { Route as TorreSucursalesRouteImport } from './routes/torre.sucursales'
import { Route as TorreSuscripcionesRouteImport } from './routes/torre.suscripciones'
import { Route as TorreTenantsRouteImport } from './routes/torre.tenants'
import { Route as TorreVersionesRouteImport } from './routes/torre.versiones'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCentralV1SplatRouteImport } from './routes/api/central/v1/$'
import { Route as ApiMercadoV1SplatRouteImport } from './routes/api/mercado/v1/$'
import { Route as ApiReleasesAppPlatformManifestRouteImport } from './routes/api/releases/$app/$platform/manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcaRoute = ArcaRouteImport.update({
  id: '/arca',
  path: '/arca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const CierreRoute = CierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoRoute = ContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RemitosRoute = RemitosRouteImport.update({
  id: '/remitos',
  path: '/remitos',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreRoute = TorreRouteImport.update({
  id: '/torre',
  path: '/torre',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturaIdRoute = FacturaIdRouteImport.update({
  id: '/factura/$id',
  path: '/factura/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemitosIdRoute = RemitosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RemitosRoute,
} as any)
const TicketCobroIdRoute = TicketCobroIdRouteImport.update({
  id: '/ticket/$cobroId',
  path: '/ticket/$cobroId',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreIndexRoute = TorreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorreRoute,
} as any)
const TorreAppsRoute = TorreAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => TorreRoute,
} as any)
const TorreAuditoriaRoute = TorreAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => TorreRoute,
} as any)
const TorreClientesRoute = TorreClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => TorreRoute,
} as any)
const TorreConfiguracionRoute = TorreConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => TorreRoute,
} as any)
const TorreDeploymentsRoute = TorreDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => TorreRoute,
} as any)
const TorreFinanzasRoute = TorreFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => TorreRoute,
} as any)
const TorreLegalRoute = TorreLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => TorreRoute,
} as any)
const TorreLoginRoute = TorreLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TorreRoute,
} as any)
const TorrePlanesRoute = TorrePlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => TorreRoute,
} as any)
const TorreProcesadoresRoute = TorreProcesadoresRouteImport.update({
  id: '/procesadores',
  path: '/procesadores',
  getParentRoute: () => TorreRoute,
} as any)
const TorreProductosRoute = TorreProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => TorreRoute,
} as any)
const TorrePromocionesRoute = TorrePromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => TorreRoute,
} as any)
const TorrePublicidadRoute = TorrePublicidadRouteImport.update({
  id: '/publicidad',
  path: '/publicidad',
  getParentRoute: () => TorreRoute,
} as any)
const TorreServiciosRoute = TorreServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => TorreRoute,
} as any)
const TorreSucursalesRoute = TorreSucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => TorreRoute,
} as any)
const TorreSuscripcionesRoute = TorreSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => TorreRoute,
} as any)
const TorreTenantsRoute = TorreTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => TorreRoute,
} as any)
const TorreVersionesRoute = TorreVersionesRouteImport.update({
  id: '/versiones',
  path: '/versiones',
  getParentRoute: () => TorreRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCentralV1SplatRoute = ApiCentralV1SplatRouteImport.update({
  id: '/api/central/v1/$',
  path: '/api/central/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadoV1SplatRoute = ApiMercadoV1SplatRouteImport.update({
  id: '/api/mercado/v1/$',
  path: '/api/mercado/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesAppPlatformManifestRoute =
  ApiReleasesAppPlatformManifestRouteImport.update({
    id: '/api/releases/$app/$platform/manifest',
    path: '/api/releases/$app/$platform/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arca': typeof ArcaRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/torre': typeof TorreRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/torre/apps': typeof TorreAppsRoute
  '/torre/auditoria': typeof TorreAuditoriaRoute
  '/torre/clientes': typeof TorreClientesRoute
  '/torre/configuracion': typeof TorreConfiguracionRoute
  '/torre/deployments': typeof TorreDeploymentsRoute
  '/torre/finanzas': typeof TorreFinanzasRoute
  '/torre/legal': typeof TorreLegalRoute
  '/torre/login': typeof TorreLoginRoute
  '/torre/planes': typeof TorrePlanesRoute
  '/torre/procesadores': typeof TorreProcesadoresRoute
  '/torre/productos': typeof TorreProductosRoute
  '/torre/promociones': typeof TorrePromocionesRoute
  '/torre/publicidad': typeof TorrePublicidadRoute
  '/torre/servicios': typeof TorreServiciosRoute
  '/torre/sucursales': typeof TorreSucursalesRoute
  '/torre/suscripciones': typeof TorreSuscripcionesRoute
  '/torre/tenants': typeof TorreTenantsRoute
  '/torre/versiones': typeof TorreVersionesRoute
  '/torre/': typeof TorreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/central/v1/$': typeof ApiCentralV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
  '/api/releases/$app/$platform/manifest': typeof ApiReleasesAppPlatformManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arca': typeof ArcaRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/torre/apps': typeof TorreAppsRoute
  '/torre/auditoria': typeof TorreAuditoriaRoute
  '/torre/clientes': typeof TorreClientesRoute
  '/torre/configuracion': typeof TorreConfiguracionRoute
  '/torre/deployments': typeof TorreDeploymentsRoute
  '/torre/finanzas': typeof TorreFinanzasRoute
  '/torre/legal': typeof TorreLegalRoute
  '/torre/login': typeof TorreLoginRoute
  '/torre/planes': typeof TorrePlanesRoute
  '/torre/procesadores': typeof TorreProcesadoresRoute
  '/torre/productos': typeof TorreProductosRoute
  '/torre/promociones': typeof TorrePromocionesRoute
  '/torre/publicidad': typeof TorrePublicidadRoute
  '/torre/servicios': typeof TorreServiciosRoute
  '/torre/sucursales': typeof TorreSucursalesRoute
  '/torre/suscripciones': typeof TorreSuscripcionesRoute
  '/torre/tenants': typeof TorreTenantsRoute
  '/torre/versiones': typeof TorreVersionesRoute
  '/torre': typeof TorreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/central/v1/$': typeof ApiCentralV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
  '/api/releases/$app/$platform/manifest': typeof ApiReleasesAppPlatformManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arca': typeof ArcaRoute
  '/auditoria': typeof AuditoriaRoute
  '/caja': typeof CajaRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/portal': typeof PortalRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/remitos': typeof RemitosRouteWithChildren
  '/torre': typeof TorreRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/vendedor': typeof VendedorRoute
  '/factura/$id': typeof FacturaIdRoute
  '/remitos/$id': typeof RemitosIdRoute
  '/ticket/$cobroId': typeof TicketCobroIdRoute
  '/torre/apps': typeof TorreAppsRoute
  '/torre/auditoria': typeof TorreAuditoriaRoute
  '/torre/clientes': typeof TorreClientesRoute
  '/torre/configuracion': typeof TorreConfiguracionRoute
  '/torre/deployments': typeof TorreDeploymentsRoute
  '/torre/finanzas': typeof TorreFinanzasRoute
  '/torre/legal': typeof TorreLegalRoute
  '/torre/login': typeof TorreLoginRoute
  '/torre/planes': typeof TorrePlanesRoute
  '/torre/procesadores': typeof TorreProcesadoresRoute
  '/torre/productos': typeof TorreProductosRoute
  '/torre/promociones': typeof TorrePromocionesRoute
  '/torre/publicidad': typeof TorrePublicidadRoute
  '/torre/servicios': typeof TorreServiciosRoute
  '/torre/sucursales': typeof TorreSucursalesRoute
  '/torre/suscripciones': typeof TorreSuscripcionesRoute
  '/torre/tenants': typeof TorreTenantsRoute
  '/torre/versiones': typeof TorreVersionesRoute
  '/torre/': typeof TorreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/central/v1/$': typeof ApiCentralV1SplatRoute
  '/api/mercado/v1/$': typeof ApiMercadoV1SplatRoute
  '/api/releases/$app/$platform/manifest': typeof ApiReleasesAppPlatformManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arca'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/contrato'
    | '/dashboard'
    | '/login'
    | '/mercado'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/torre'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/torre/apps'
    | '/torre/auditoria'
    | '/torre/clientes'
    | '/torre/configuracion'
    | '/torre/deployments'
    | '/torre/finanzas'
    | '/torre/legal'
    | '/torre/login'
    | '/torre/planes'
    | '/torre/procesadores'
    | '/torre/productos'
    | '/torre/promociones'
    | '/torre/publicidad'
    | '/torre/servicios'
    | '/torre/sucursales'
    | '/torre/suscripciones'
    | '/torre/tenants'
    | '/torre/versiones'
    | '/torre/'
    | '/api/auth/$'
    | '/api/central/v1/$'
    | '/api/mercado/v1/$'
    | '/api/releases/$app/$platform/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arca'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/contrato'
    | '/dashboard'
    | '/login'
    | '/mercado'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/torre/apps'
    | '/torre/auditoria'
    | '/torre/clientes'
    | '/torre/configuracion'
    | '/torre/deployments'
    | '/torre/finanzas'
    | '/torre/legal'
    | '/torre/login'
    | '/torre/planes'
    | '/torre/procesadores'
    | '/torre/productos'
    | '/torre/promociones'
    | '/torre/publicidad'
    | '/torre/servicios'
    | '/torre/sucursales'
    | '/torre/suscripciones'
    | '/torre/tenants'
    | '/torre/versiones'
    | '/torre'
    | '/api/auth/$'
    | '/api/central/v1/$'
    | '/api/mercado/v1/$'
    | '/api/releases/$app/$platform/manifest'
  id:
    | '__root__'
    | '/'
    | '/arca'
    | '/auditoria'
    | '/caja'
    | '/cierre'
    | '/clientes'
    | '/contrato'
    | '/dashboard'
    | '/login'
    | '/mercado'
    | '/portal'
    | '/productos'
    | '/proveedores'
    | '/recuperar'
    | '/registro'
    | '/remitos'
    | '/torre'
    | '/usuarios'
    | '/vendedor'
    | '/factura/$id'
    | '/remitos/$id'
    | '/ticket/$cobroId'
    | '/torre/apps'
    | '/torre/auditoria'
    | '/torre/clientes'
    | '/torre/configuracion'
    | '/torre/deployments'
    | '/torre/finanzas'
    | '/torre/legal'
    | '/torre/login'
    | '/torre/planes'
    | '/torre/procesadores'
    | '/torre/productos'
    | '/torre/promociones'
    | '/torre/publicidad'
    | '/torre/servicios'
    | '/torre/sucursales'
    | '/torre/suscripciones'
    | '/torre/tenants'
    | '/torre/versiones'
    | '/torre/'
    | '/api/auth/$'
    | '/api/central/v1/$'
    | '/api/mercado/v1/$'
    | '/api/releases/$app/$platform/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcaRoute: typeof ArcaRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CajaRoute: typeof CajaRoute
  CierreRoute: typeof CierreRoute
  ClientesRoute: typeof ClientesRoute
  ContratoRoute: typeof ContratoRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  PortalRoute: typeof PortalRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RemitosRoute: typeof RemitosRouteWithChildren
  TorreRoute: typeof TorreRouteWithChildren
  UsuariosRoute: typeof UsuariosRoute
  VendedorRoute: typeof VendedorRoute
  FacturaIdRoute: typeof FacturaIdRoute
  TicketCobroIdRoute: typeof TicketCobroIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCentralV1SplatRoute: typeof ApiCentralV1SplatRoute
  ApiMercadoV1SplatRoute: typeof ApiMercadoV1SplatRoute
  ApiReleasesAppPlatformManifestRoute: typeof ApiReleasesAppPlatformManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arca': {
      id: '/arca'
      path: '/arca'
      fullPath: '/arca'
      preLoaderRoute: typeof ArcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cierre': {
      id: '/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof CierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato': {
      id: '/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof ContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remitos': {
      id: '/remitos'
      path: '/remitos'
      fullPath: '/remitos'
      preLoaderRoute: typeof RemitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre': {
      id: '/torre'
      path: '/torre'
      fullPath: '/torre'
      preLoaderRoute: typeof TorreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factura/$id': {
      id: '/factura/$id'
      path: '/factura/$id'
      fullPath: '/factura/$id'
      preLoaderRoute: typeof FacturaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remitos/$id': {
      id: '/remitos/$id'
      path: '/$id'
      fullPath: '/remitos/$id'
      preLoaderRoute: typeof RemitosIdRouteImport
      parentRoute: typeof RemitosRoute
    }
    '/ticket/$cobroId': {
      id: '/ticket/$cobroId'
      path: '/ticket/$cobroId'
      fullPath: '/ticket/$cobroId'
      preLoaderRoute: typeof TicketCobroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre/': {
      id: '/torre/'
      path: '/'
      fullPath: '/torre/'
      preLoaderRoute: typeof TorreIndexRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/apps': {
      id: '/torre/apps'
      path: '/apps'
      fullPath: '/torre/apps'
      preLoaderRoute: typeof TorreAppsRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/auditoria': {
      id: '/torre/auditoria'
      path: '/auditoria'
      fullPath: '/torre/auditoria'
      preLoaderRoute: typeof TorreAuditoriaRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/clientes': {
      id: '/torre/clientes'
      path: '/clientes'
      fullPath: '/torre/clientes'
      preLoaderRoute: typeof TorreClientesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/configuracion': {
      id: '/torre/configuracion'
      path: '/configuracion'
      fullPath: '/torre/configuracion'
      preLoaderRoute: typeof TorreConfiguracionRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/deployments': {
      id: '/torre/deployments'
      path: '/deployments'
      fullPath: '/torre/deployments'
      preLoaderRoute: typeof TorreDeploymentsRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/finanzas': {
      id: '/torre/finanzas'
      path: '/finanzas'
      fullPath: '/torre/finanzas'
      preLoaderRoute: typeof TorreFinanzasRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/legal': {
      id: '/torre/legal'
      path: '/legal'
      fullPath: '/torre/legal'
      preLoaderRoute: typeof TorreLegalRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/login': {
      id: '/torre/login'
      path: '/login'
      fullPath: '/torre/login'
      preLoaderRoute: typeof TorreLoginRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/planes': {
      id: '/torre/planes'
      path: '/planes'
      fullPath: '/torre/planes'
      preLoaderRoute: typeof TorrePlanesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/procesadores': {
      id: '/torre/procesadores'
      path: '/procesadores'
      fullPath: '/torre/procesadores'
      preLoaderRoute: typeof TorreProcesadoresRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/productos': {
      id: '/torre/productos'
      path: '/productos'
      fullPath: '/torre/productos'
      preLoaderRoute: typeof TorreProductosRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/promociones': {
      id: '/torre/promociones'
      path: '/promociones'
      fullPath: '/torre/promociones'
      preLoaderRoute: typeof TorrePromocionesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/publicidad': {
      id: '/torre/publicidad'
      path: '/publicidad'
      fullPath: '/torre/publicidad'
      preLoaderRoute: typeof TorrePublicidadRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/servicios': {
      id: '/torre/servicios'
      path: '/servicios'
      fullPath: '/torre/servicios'
      preLoaderRoute: typeof TorreServiciosRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/sucursales': {
      id: '/torre/sucursales'
      path: '/sucursales'
      fullPath: '/torre/sucursales'
      preLoaderRoute: typeof TorreSucursalesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/suscripciones': {
      id: '/torre/suscripciones'
      path: '/suscripciones'
      fullPath: '/torre/suscripciones'
      preLoaderRoute: typeof TorreSuscripcionesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/tenants': {
      id: '/torre/tenants'
      path: '/tenants'
      fullPath: '/torre/tenants'
      preLoaderRoute: typeof TorreTenantsRouteImport
      parentRoute: typeof TorreRoute
    }
    '/torre/versiones': {
      id: '/torre/versiones'
      path: '/versiones'
      fullPath: '/torre/versiones'
      preLoaderRoute: typeof TorreVersionesRouteImport
      parentRoute: typeof TorreRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/central/v1/$': {
      id: '/api/central/v1/$'
      path: '/api/central/v1/$'
      fullPath: '/api/central/v1/$'
      preLoaderRoute: typeof ApiCentralV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercado/v1/$': {
      id: '/api/mercado/v1/$'
      path: '/api/mercado/v1/$'
      fullPath: '/api/mercado/v1/$'
      preLoaderRoute: typeof ApiMercadoV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases/$app/$platform/manifest': {
      id: '/api/releases/$app/$platform/manifest'
      path: '/api/releases/$app/$platform/manifest'
      fullPath: '/api/releases/$app/$platform/manifest'
      preLoaderRoute: typeof ApiReleasesAppPlatformManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RemitosRouteChildren {
  RemitosIdRoute: typeof RemitosIdRoute
}

const RemitosRouteChildren: RemitosRouteChildren = {
  RemitosIdRoute: RemitosIdRoute,
}

const RemitosRouteWithChildren =
  RemitosRoute._addFileChildren(RemitosRouteChildren)

interface TorreRouteChildren {
  TorreAppsRoute: typeof TorreAppsRoute
  TorreAuditoriaRoute: typeof TorreAuditoriaRoute
  TorreClientesRoute: typeof TorreClientesRoute
  TorreConfiguracionRoute: typeof TorreConfiguracionRoute
  TorreDeploymentsRoute: typeof TorreDeploymentsRoute
  TorreFinanzasRoute: typeof TorreFinanzasRoute
  TorreLegalRoute: typeof TorreLegalRoute
  TorreLoginRoute: typeof TorreLoginRoute
  TorrePlanesRoute: typeof TorrePlanesRoute
  TorreProcesadoresRoute: typeof TorreProcesadoresRoute
  TorreProductosRoute: typeof TorreProductosRoute
  TorrePromocionesRoute: typeof TorrePromocionesRoute
  TorrePublicidadRoute: typeof TorrePublicidadRoute
  TorreServiciosRoute: typeof TorreServiciosRoute
  TorreSucursalesRoute: typeof TorreSucursalesRoute
  TorreSuscripcionesRoute: typeof TorreSuscripcionesRoute
  TorreTenantsRoute: typeof TorreTenantsRoute
  TorreVersionesRoute: typeof TorreVersionesRoute
  TorreIndexRoute: typeof TorreIndexRoute
}

const TorreRouteChildren: TorreRouteChildren = {
  TorreAppsRoute: TorreAppsRoute,
  TorreAuditoriaRoute: TorreAuditoriaRoute,
  TorreClientesRoute: TorreClientesRoute,
  TorreConfiguracionRoute: TorreConfiguracionRoute,
  TorreDeploymentsRoute: TorreDeploymentsRoute,
  TorreFinanzasRoute: TorreFinanzasRoute,
  TorreLegalRoute: TorreLegalRoute,
  TorreLoginRoute: TorreLoginRoute,
  TorrePlanesRoute: TorrePlanesRoute,
  TorreProcesadoresRoute: TorreProcesadoresRoute,
  TorreProductosRoute: TorreProductosRoute,
  TorrePromocionesRoute: TorrePromocionesRoute,
  TorrePublicidadRoute: TorrePublicidadRoute,
  TorreServiciosRoute: TorreServiciosRoute,
  TorreSucursalesRoute: TorreSucursalesRoute,
  TorreSuscripcionesRoute: TorreSuscripcionesRoute,
  TorreTenantsRoute: TorreTenantsRoute,
  TorreVersionesRoute: TorreVersionesRoute,
  TorreIndexRoute: TorreIndexRoute,
}

const TorreRouteWithChildren = TorreRoute._addFileChildren(TorreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcaRoute: ArcaRoute,
  AuditoriaRoute: AuditoriaRoute,
  CajaRoute: CajaRoute,
  CierreRoute: CierreRoute,
  ClientesRoute: ClientesRoute,
  ContratoRoute: ContratoRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  PortalRoute: PortalRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RemitosRoute: RemitosRouteWithChildren,
  TorreRoute: TorreRouteWithChildren,
  UsuariosRoute: UsuariosRoute,
  VendedorRoute: VendedorRoute,
  FacturaIdRoute: FacturaIdRoute,
  TicketCobroIdRoute: TicketCobroIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCentralV1SplatRoute: ApiCentralV1SplatRoute,
  ApiMercadoV1SplatRoute: ApiMercadoV1SplatRoute,
  ApiReleasesAppPlatformManifestRoute: ApiReleasesAppPlatformManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
